language: haskell
ghc: 7.6

sudo: required

before_install:
  - sudo apt-get update -qy
  - sudo apt-get install -qq build-essential ncurses-dev haskell-platform

script:
  - cabal update
  - cabal install bimap bitset parse-dimacs hxt-relaxng text-0.11.3.1
  - cabal install hatt fgl graphviz
  - cabal install syb MissingH yaml
  - make test-products
