# language: haskell
ghc: 7.6

sudo: required

env:
  - CABALVER=1.16 GHCVER=7.6.3

before_install:
  - sudo apt-get update -qy
  - sudo apt-get install -qq build-essential ncurses-dev haskell-platform

script:
  - cabal update
  - cabal install bimap bitset parse-dimacs hxt-relaxng text-0.11.3.1
  - cabal install hatt fgl graphviz
  - cabal install syb MissingH
  - make test-products
