# language: haskell
ghc: 7.6

sudo: required

env:
  - CABALVER=1.16 GHCVER=7.6.3

before_install:
  - sudo apt-get update -qy  
  - sudo apt-get install -qq build-essential ncurses-dev

script:  
  - sudo ./env-config.sh  


# https://github.com/hvr/multi-ghc-travis
# https://downloads.haskell.org/~ghc/7.0.4/docs/html/Cabal/authors.html