ghc: 7.6

before_install:
  - apt-get update -qy
  - apt-get install -qq build-essential libghc-ncurses-dev ncurses-dev

script:
  - cabal install bimap bitset parse-dimacs hxt-relaxng
  - cabal install hatt fgl graphviz
  - cabal install syb MissingH

